### ISSUE TITLE
On click listener on the text lable

### ISSUE THREAD

**Issue by Neustart** [Clans/FloatingActionButton#121]
Hi. How can i add onClickListner to text label in action menu item? 
i can setOnClickListener to ActionMenu value, but in this case it can only responds when i  pressing on icon. 
Thank you.

**Comment by Clans** [comment]
Just set yout OnClickListener on FAB inside the menu and label will also become clickable.

**Comment by Neustart** [comment]
Can u explain more detailed ?
Look, this is how i create listner:
FloatingActionButton actionMenu = new FloatingActionButton(getApplicationContext());
actionMenu.setOnClickListener(new View.OnClickListener(){...}
Where i need to set listner to do label clicable ?

**Comment by Clans** [comment]
Labels are enabled only if the FAB is placed inside the FAM.

**Comment by jzeferino** [comment]
I've already added the OnClickListener inside the menu and the label keeps unresponsive to click.

**Comment by Neustart** [comment]
Me too, my FAB placed iside te FAM

**Comment by Clans** [comment]
Please paste your code here so I could look at it.

**Comment by jzeferino** [comment]
This happens to me only if the FAB is added programmaticlly. When added in XML it works.

**Comment by Clans** [comment]
There's an example of how to add FAB programmatically. Please look at the `sample`'s module code.

**Comment by jzeferino** [comment]
i'm doing like this: 
or (final Sport sport : Sport.values()) {
   FloatingActionButton fab = new FloatingActionButton(getActivity());
   fab.setImageResource(sport.getResource());
   fab.setLabelText(getString(sport.getName()));
 
   fab.setColorNormal(ContextCompat.getColor(getActivity(), R.color.accent));
   fab.setColorRipple(ContextCompat.getColor(getActivity(), R.color.primary_dark));
   fab.setColorPressed(ContextCompat.getColor(getActivity(), R.color.primary_dark));
   fab.setButtonSize(FloatingActionButton.SIZE_MINI);
   fab.setOnClickListener(new View.OnClickListener() {
       @Override
       public void onClick(View v) {
           createNewChallenge(sport);
       }
   });
   mFabMenu.addMenuButton(fab);
}

**Comment by dtarianyk** [comment]
Thanks! Will fix this in the next build. For now set your OnClickListener after you have added the FAB into the FAM.

**Comment by Clans** [comment]
Thanks! Will fix this in the next build. For now set your OnClickListener after you have added the FAB into the FAM.

**Comment by odyodyodys** [comment]
This is **not fixed**.
While the label is now clickable, it triggers the event with the label's view as an argument, and not the fab's view and you can't use it since its not possible to relate it to its fab.

If you use the code from @jzeferino's comment the bug is there.
A workaround using version 1.6.4 is to:
- create the button instance
- add the button to the menu and
- then add the listener (should be last)

This bug is result of the workflow of it. The logic should be to create, configure and then attach it. Not create, attach and then configure. One good and permanent solution could be to use the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) for adding menu items.
