### ISSUE TITLE
Adding an option to display FloatingMenu at the bottom of the FAB and not at the top.

### ISSUE THREAD

**Issue by ChristopheVersieux** [Clans/FloatingActionButton#34]
I haven't seen any mention of this case in the guidelines, or in a Google app, but would be nice if the menu could open at the bottom of the primary FAB.

In some cases, the FAB is in the upper part of the screen , and the Menu items needs to be below, which is I think not supported by your lib (yet?)

Will try to find an exemple or a picture and add it here, but I hope you understand what I mean.

Thanks for your work!

**Comment by Clans** [comment]
Added to my ToDo list.

**Comment by DavideSteduto** [comment]
Dear Clans, how is the status of this functionality? Since your library is very well in-nested with my app already I would prefer to keep this hard work and not changing library.
I have looked into your code, I think the necessary changes are in onMeasure and in onLayout, but I tried without success to do it myself, even if something I was able to add. Like some new attrs and doing some simple calculations, but I am not very good in custom Layouts ;-) especially if it's not my original code.
I will be waiting with impatience this your new functionality.

Thanks for you good work.

**Comment by Clans** [comment]
Currently working on a new functionality. Will do my best to implement your request asap.

**Comment by DavideSteduto** [comment]
That and the progress bar new features are really great. Magnificent work, I think your library is the best, very simple and clean.

**Comment by Clans** [comment]
Thank you!
